FROM python:3.12
#LABEL authors="David Kadish"

ENV DASH_DEBUG_MODE True

WORKDIR /code

COPY pyproject.toml /code/pyproject.toml
COPY poetry.lock /code/poetry.lock

RUN pip install poetry poetry-plugin-export
RUN poetry export --only main --without-hashes --output /code/requirements.txt
RUN pip install --no-deps --no-cache-dir -r requirements.txt

COPY app.py /code/app.py
COPY config.py /code/config.py
COPY pages/ /code/pages/
COPY utils/ /code/utils/
COPY menu/ /code/menu/
COPY content/ /code/content/
COPY assets/ /code/assets/

EXPOSE 8051
CMD ["gunicorn", "-b", "0.0.0.0:8051", "--timeout=600", "app:server"]
