FROM python:3.12

ENV DASH_DEBUG_MODE False

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates
ADD https://astral.sh/uv/0.7.13/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && rm /uv-installer.sh
ENV PATH="/root/.local/bin/:$PATH"

ADD . /code
WORKDIR /code

RUN uv sync --locked

EXPOSE 8051
CMD ["uv", "run", "--with", "gunicorn", "gunicorn", "--bind", "0.0.0.0:8051", "--timeout=600", "app:server"]
