FROM python:3.12
#LABEL authors="David Kadish"

ENV DASH_DEBUG_MODE False

WORKDIR /code

COPY requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY app.py /code/app.py
COPY config.py /code/config.py
COPY pages/ /code/pages/
COPY utils/ /code/utils/
COPY menu/ /code/menu/
COPY content/ /code/content/
COPY assets/ /code/assets/

EXPOSE 8050
CMD ["gunicorn", "-b", "0.0.0.0:8050", "--timeout=600", "app:server"]
